name: "Release Cop Notify Action"
description: "Github Action that notifies the new Release Cop to Slack."
inputs:
  opsgenie-api-token:
    description: "OpsGenie API token"
    required: true
  opsgenie-schedule-id:
    description: "OpsGenie Schedule ID"
    required: true
  slack-webhook-url:
    description: "URL to send Slack webhooks to"
    required: true
runs:
  using: "node16"
  main: "index.js"
