name: "PagerDuty OnCall Slack Action"
description: "Github Action that posts the PagerDuty oncall person to Slack."
inputs:
  pagerduty-api-token:
    description: "PagerDuty API user token"
    required: true
  pagerduty-schedule-id:
    description: "PagerDuty Schedule ID"
    required: true
  slack-webhook-url:
    description: "URL to send Slack webhooks to"
    required: true
runs:
  using: "node16"
  main: "index.js"
